name: Run Gemini CLI

on:
  workflow_dispatch:  # 수동 실행 트리거

jobs:
  run-gemini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'x x

      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli

      - name: Create locales directory inside src
        run: mkdir -p src/locales

      - name: Run Gemini CLI

        run: |
          echo "I want to extract UI text from my TSX files and generate i18n key-value pairs in English in JSON format. \
          Please follow this key naming convention: use the component file name (without extension) as the prefix, followed by the key name. \
          For example, if the file is components/Login.tsx and the text is 'Click Me!', the key should be 'login.clickMe'. Do not use nested JSON \
          This is running in a GitHub Actions environment, so do not print anything until all processing is complete. \
          Return only the final result in valid JSON format, without any explanations, code snippets, or repeated prompts." \
          | gemini > src/locales/generated.txt

        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Extract valid JSON from Gemini output
        run: |
          # Extract JSON block from raw_output.txt and save to generated.json
          datetime=$(date +"%Y%m%d_%H%M%S")
          filename="generated_$datetime.json"
          
           awk '/```json/{f=1;next} /```/{f=0} f' src/locales/generated.txt > "src/locales/$filename"


#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v3
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#
#      - name: Upload to S3
#        run: |
#          aws s3 cp "src/locales/$filename" s3://i18n-automation/test/ --acl public-read

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Add generated locales"
          git push
